---
settings:
  name: Google Cloud Storage
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documents relatifs à Google Cloud Storage
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Consultez vos compartiments de stockage Google Cloud
      url: "/task-viewing-gcp-storage.html"
  - title: Gestion des compartiments de stockage Google Cloud
    entries:
    - title: Ajouter de nouveaux compartiments
      url: "/task-add-gcp-bucket.html"
    - title: Modifier les paramètres du godet
      url: "/task-change-gcp-bucket-settings.html"
    - title: Utilisez les services de données NetApp avec des compartiments de stockage
        Google Cloud
      url: "/task-gcp-enable-data-services.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Consultez vos compartiments de stockage Google Cloud
      url: task-viewing-gcp-storage.html
  - title: Gestion des compartiments de stockage Google Cloud
    links:
    - title: Ajouter des compartiments
      url: task-add-gcp-bucket.html
    - title: Modifier les paramètres du godet
      url: task-change-gcp-bucket-settings.html
    - title: Utilisez les services de données NetApp avec des compartiments de stockage
        Google Cloud
      url: task-gcp-enable-data-services.html
  - title: Plus d'informations
    links:
    - title: Documentation Google Cloud Storage pour la gestion hors de BlueXP
      url: https://cloud.google.com/storage/docs/creating-buckets
  - title: Blogs et communauté
    links:
    - title: Communauté NetApp
      url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
    - title: Blog BlueXP
      url: https://bluexp.netapp.com/blog/topic/cloud-manager
    - title: Webinaires sur le cloud
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: 7a45e6298bb69116e2c6db653fb88884
